default_stages: [pre-commit, pre-push]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.4
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
  - id: pytest-check
    stages: [pre-push]
    types: [python]
    name: pytest-check
    entry: python -m pytest -v tests/
    language: system
    pass_filenames: false
    always_run: true