"""expense, scenario, and joint table

Revision ID: 5cdc67766842
Revises: a11f326d87b6
Create Date: 2024-11-19 10:05:50.336462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdc67766842'
down_revision = 'a11f326d87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['end_year'], ['age.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['start_year'], ['age.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_owner_id'), ['owner_id'], unique=False)

    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_owner_id'), ['owner_id'], unique=False)

    op.create_table('scenario_expense',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('upper_raise_rate', sa.Numeric(), nullable=False),
    sa.Column('lower_raise_rate', sa.Numeric(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_year'], ['age.id'], ),
    sa.ForeignKeyConstraint(['left_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['start_year'], ['age.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    op.drop_table('scenario_expense')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_owner_id'))

    op.drop_table('scenario')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_owner_id'))

    op.drop_table('expense')
    # ### end Alembic commands ###
