"""update House table

Revision ID: 7319e6001c3b
Revises: deb6d0f2165a
Create Date: 2024-11-21 20:56:52.575303

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7319e6001c3b"
down_revision = "deb6d0f2165a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.add_column(sa.Column("down_payment", sa.Numeric(), nullable=False))
        batch_op.alter_column(
            "interest",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(),
            existing_nullable=False,
        )

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.add_column(sa.Column("down_payment", sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column("interest", sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column("loan_term", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.drop_column("loan_term")
        batch_op.drop_column("interest")
        batch_op.drop_column("down_payment")

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.alter_column(
            "interest",
            existing_type=sa.Numeric(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("down_payment")

    # ### end Alembic commands ###
