"""child and joint table

Revision ID: 8a5688e104c2
Revises: f3293807bb2b
Create Date: 2024-11-19 17:50:38.646200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5688e104c2'
down_revision = 'f3293807bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('born_at_age', sa.Integer(), nullable=False),
    sa.Column('independent_year', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['born_at_age'], ['age.id'], ),
    sa.ForeignKeyConstraint(['independent_year'], ['age.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_owner_id'), ['owner_id'], unique=False)

    op.create_table('scenario_child',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('born_at_age', sa.Integer(), nullable=False),
    sa.Column('independent_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['born_at_age'], ['age.id'], ),
    sa.ForeignKeyConstraint(['independent_year'], ['age.id'], ),
    sa.ForeignKeyConstraint(['left_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_child')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_owner_id'))

    op.drop_table('child')
    # ### end Alembic commands ###
