"""house and joint table

Revision ID: f3293807bb2b
Revises: 7d501a31a8e3
Create Date: 2024-11-19 17:28:34.536467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3293807bb2b'
down_revision = '7d501a31a8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=False),
    sa.Column('loan_term', sa.Integer(), nullable=False),
    sa.Column('buy_at_age', sa.Integer(), nullable=False),
    sa.Column('sell_at_age', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buy_at_age'], ['age.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sell_at_age'], ['age.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_house_owner_id'), ['owner_id'], unique=False)

    op.create_table('scenario_house',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('buy_at_age', sa.Integer(), nullable=False),
    sa.Column('sell_at_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_at_age'], ['age.id'], ),
    sa.ForeignKeyConstraint(['left_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['sell_at_age'], ['age.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_house')
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_house_owner_id'))

    op.drop_table('house')
    # ### end Alembic commands ###
