"""expense, scenario, and joint table

Revision ID: f8875e3d410e
Revises: a11f326d87b6
Create Date: 2024-11-18 22:07:25.621330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8875e3d410e'
down_revision = 'a11f326d87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_expense',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('upper_raise_rate', sa.Numeric(), nullable=False),
    sa.Column('lower_raise_rate', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    op.drop_table('scenario_expense')
    op.drop_table('scenario')
    op.drop_table('expense')
    # ### end Alembic commands ###
